Modelos/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("registrodeclientes/", nuevos_clientes),
    path("clientes/", ver_clientes),
    path("borrarcliente/<cliente_id>", borrar_cliente),
    path("editarcliente/<cliente_id>", editar_cliente)

]

RegistroDeClientes/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", inicio),
    path("", include("Modelos.urls")),
    path("login/", login_request),
    path("registro/", registro),
    path('logout/', LogoutView.as_view(template_name='inicio.html'), name="Logout"),
    path("perfil/", perfilView),
    path("editarperfil/", editarperfil),
    path("cambiarcontraseña/", cambiarpassword)


]

Modelos/models.py
from django.db import models

class Clientes (models.Model):
    mail = models.EmailField()
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=40)
    fecha_registro = models.DateField()

    class Meta:
        verbose_name_plural = "Clientes"

# Create your models here.

Modelos/forms.py
from django import forms

class EditarClientes(forms.Form):
    nombre = forms.CharField(max_length=30)
    apellido = forms.CharField(max_length=40)
    mail = forms.EmailField()
    fecha_registro = forms.DateField()

RegistroDeClientes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User

class registrousuario(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget= forms.PasswordInput())
    password2 = forms.CharField(label="Repetir contraseña", widget= forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

class UserEditForm(UserChangeForm):
    username = forms.CharField(widget = forms.TextInput(attrs = {'placeholder': 'Username'}))
    email = forms.EmailField(widget = forms.TextInput(attrs = {'placeholder': 'Email'}))
    first_name = forms.CharField(widget = forms.TextInput(attrs = {'placeholder': 'First Name'}))
    last_name = forms.CharField(widget = forms.TextInput(attrs = {'placeholder': 'Last Name'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        help_texts = {k:"" for k in fields}

class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label ="", widget= forms.PasswordInput(attrs={'placeholder': "Contraseña anterior"}))
    new_password1 = forms.CharField(label ="", widget= forms.PasswordInput(attrs={'placeholder': "Contraseña nueva"}))
    new_password2 = forms.CharField(label ="", widget= forms.PasswordInput(attrs={'placeholder': "Confirmar contraseña nueva"}))

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']
        help_texts = {k:"" for k in fields}

Modelos/views.py
from django.shortcuts import render
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import *

#Con esta función vamos a registrar nuevos clientes.
def nuevos_clientes(request):
    try:
        if request.method == 'POST':
            nuevo_cliente = Clientes(mail=request.POST["mail"], nombre=request.POST["nombre"], apellido=request.POST["apellido"], fecha_registro=request.POST["fecha_registro"])
            nuevo_cliente.save()
            return render(request, "clientes.html")
    except:
        return render(request, "clientes.html")
    return render(request, "clientes.html")


#Con esta función vamos a poder ver todos los clientes de la base de datos.
@login_required
def ver_clientes(request):
    clientes = Clientes.objects.all()
    return render(request, "verclientes.html", {"clientes": clientes})

#Con esta función vamos a poder ver eliminar clientes de la base de datos.
@login_required
def borrar_cliente(request, cliente_id):
    clientes = Clientes.objects.get(id = cliente_id)
    clientes.delete()

    clientes = Clientes.objects.all()
    return render(request, "verclientes.html", {"clientes": clientes})

#Con esta función vamos a poder ver editar clientes de la base de datos.
@login_required
def editar_cliente(request, cliente_id):
    cliente = Clientes.objects.get(id=cliente_id)

    if request.method == 'POST':
        formulario = EditarClientes(request.POST)
        if formulario.is_valid():
            info = formulario.cleaned_data
            cliente.mail = info["mail"]
            cliente.nombre = info["nombre"]
            cliente.apellido = info["apellido"]
            cliente.fecha_registro = info["fecha_registro"]
            cliente.save()
            cliente = Clientes.objects.all()
            return render(request, "verclientes.html", {"clientes":cliente})
    else:
        formulario = EditarClientes(initial={'nombre': cliente.nombre, 'apellido': cliente.apellido, 'mail': cliente.mail, "fecha_registro": cliente.fecha_registro})
    return render(request, "editarcliente.html", {"formulario": formulario})

RegistroDeClientes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import registrousuario, UserEditForm, ChangePasswordForm

def inicio(request):
    return render(request, "inicio.html")

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.cleaned_data.get('username')
            pwd = form.cleaned_data.get('password')

            user = authenticate(username=user, password=pwd)

            if user is not None:
                login(request, user)

                return render(request, 'clientes.html')

            else:
                return render(request, "login.html", {'form': form})
        else:
            return render(request, "login.html", {'form': form})
    form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def registro(request):
    form = registrousuario(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect("/login/")
        else:
            return render(request, "registro.html", {'form': form})

    form = registrousuario()
    return render(request, "registro.html", {'form': form})

@login_required
def perfilView(request):
    return render(request, 'perfil.html')

@login_required
def editarperfil(request):
    usuario = request.user
    user_info = User.objects.get(id=usuario.id)
    if request.method == "POST":
        form = UserEditForm(request.POST, instance=usuario)
        if form.is_valid():
            user_info.username = form.cleaned_data.get('username')
            user_info.email = form.cleaned_data.get('email')
            user_info.first_name = form.cleaned_data.get('first_name')
            user_info.last_name = form.cleaned_data.get('last_name')
            user_info.save()
            return render(request, "perfil.html")
        else:
            return render(request, "login.html", {'form': form})
    else:
        form = UserEditForm(
            initial={'email': usuario.email, 'username': usuario.username, 'first_name': usuario.first_name,
                     'last_name': usuario.last_name})
    return render(request, "editarperfil.html", {'form': form, 'usuario': usuario})


@login_required
def cambiarpassword(request):
    usuario = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(data=request.POST, user=usuario)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return render(request, 'perfil.html')

    else:
        form = ChangePasswordForm(data=request.POST, user=usuario)
    return render(request, 'cambiarcontraseña.html', {'form': form, 'usuario': usuario})

Modelos/templates/clientes.html
<!DOCTYPE html>
<html>
<head>
	<title>Formulario de Clientes</title>
	<style>
		body {
			background-color: #f2f2f2;
			font-family: Arial, sans-serif;
			font-size: 16px;
		}

		.container {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 80vh;
		}

		.header {
			display: flex;
			justify-content: flex-end;
			padding: 10px;
			background-color: #f2f2f2;

		}

		.login-btn,
		.register-btn,
		.salir-btn,
		.perfil-btn{
			background-color: #00008B;
			color: #ffffff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			font-size: 16px;
			cursor: pointer;
			margin-left: 10px;
		}

		.login-btn:hover,
		.register-btn:hover,
		.salir-btn:hover,
		.perfil-btn:hover{
			background-color: #0062cc;
		}

		h2 {
			color: #000000;
			margin-bottom: 30px;
		}

		form {
			background-color: #B0C4DE;
			border: 1px solid #dddddd;
			padding: 20px;
			border-radius: 10px;
			box-shadow: 0 0 10px rgba(0,0,0,0.1);
			width: 400px;
			text-align: center;
		}

		label {
			display: block;
			margin-bottom: 10px;
			color: #2F4F4F;
			text-align: left;
		}

		input[type="text"],
		input[type="email"] {
			padding: 10px;
			border: 1px solid #cccccc;
			border-radius: 5px;
			width: 100%;
			box-sizing: border-box;
			margin-bottom: 20px;
			font-size: 16px;
		}

		input[type="submit"] {
			background-color: #00008B;
			color: #ffffff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			font-size: 16px;
			cursor: pointer;
		}

		input[type="submit"]:hover {
			background-color: #0062cc;
		}
	</style>
</head>
{% block contenido %}
<body>
	<div class="header">
		{% if request.user.is_authenticated %}
		<a class="perfil-btn" aria-current="page" href="http://127.0.0.1:8000/perfil/">{{user.username}}</a>
        <a class="salir-btn" aria-current="page" href="http://127.0.0.1:8000/logout/">Salir</a>
		{% endif %}
		{% if not request.user.is_authenticated %}
		<a class="login-btn" href="http://127.0.0.1:8000/login/">Login</a>
		<a class="register-btn" href="http://127.0.0.1:8000/registro/">Registro</a>
		{% endif %}
	</div>
	<div class="container">
		<form method="POST">
			{% csrf_token %}
			<h2>Registro de Nuevo Cliente</h2>
			<label for="nombre">Nombre:</label>
			<input type="text" id="nombre" name="nombre">

			<label for="apellido">Apellido:</label>
			<input type="text" id="apellido" name="apellido">

			<label for="mail">Correo Electrónico:</label>
			<input type="email" id="mail" name="mail">

			<label for="fecha_registro">Fecha de Registro:</label>
			<input type="email" id="fecha_registro" name="fecha_registro">

			<input type="submit" value="Registrar">
			<a class="login-btn" href="http://127.0.0.1:8000/clientes/">Ver Clientes</a>
		</form>
	</div>
</body>
</html>
{% endblock %}

Modelos/templates/editarcliente.html
<!DOCTYPE html>
<html>
<head>
	<title>Formulario de Clientes</title>
	<style>
		body {
			background-color: #f2f2f2;
			font-family: Arial, sans-serif;
			font-size: 16px;
		}

		.container {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 80vh;
		}

		.header {
			display: flex;
			justify-content: flex-end;
			padding: 10px;
			background-color: #f2f2f2;

		}

		.login-btn,
		.register-btn,
		.salir-btn,
		.perfil-btn,
		.inicio-btn{
			background-color: #00008B;
			color: #ffffff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			font-size: 16px;
			cursor: pointer;
			margin-left: 10px;
		}

		.login-btn:hover,
		.register-btn:hover,
		.salir-btn:hover,
		.perfil-btn:hover,
		.inicio-btn:hover{
			background-color: #0062cc;
		}

		h2 {
			color: #000000;
			margin-bottom: 30px;
		}

		form {
			background-color: #B0C4DE;
			border: 1px solid #dddddd;
			padding: 20px;
			border-radius: 10px;
			box-shadow: 0 0 10px rgba(0,0,0,0.1);
			width: 400px;
			text-align: center;
		}

		label {
			display: block;
			margin-bottom: 10px;
			color: #2F4F4F;
			text-align: left;
		}

		input[type="text"],
		input[type="email"],
		input[type="date"]{
			padding: 10px;
			border: 1px solid #cccccc;
			border-radius: 5px;
			width: 100%;
			box-sizing: border-box;
			margin-bottom: 20px;
			font-size: 16px;
		}

		input[type="submit"] {
			background-color: #00008B;
			color: #ffffff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			font-size: 16px;
			cursor: pointer;
		}

		input[type="submit"]:hover {
			background-color: #0062cc;
		}
	</style>
</head>
{% block contenido %}
<body>
	<div class="header">
		<div style="margin-right: auto; display: flex; justify-content: space-between;">
			<a class="inicio-btn" href="http://127.0.0.1:8000/">Inicio</a>
			<a class="inicio-btn" href="http://127.0.0.1:8000/registrodeclientes/">Registrar Cliente</a>
		</div>
		{% if request.user.is_authenticated %}
		<a class="perfil-btn" aria-current="page" href="http://127.0.0.1:8000/perfil/">{{user.username}}</a>
        <a class="salir-btn" aria-current="page" href="http://127.0.0.1:8000/logout/">Salir</a>
		{% endif %}
		{% if not request.user.is_authenticated %}
		<a class="login-btn" href="http://127.0.0.1:8000/login/">Login</a>
		<a class="register-btn" href="http://127.0.0.1:8000/registro/">Registro</a>
		{% endif %}
	</div>
	<div class="container">
		<form method='POST'>
			{% csrf_token %}
			<h2>EDITAR CLIENTE</h2>
            {{ formulario.as_table }}
            <button type="submit" class="perfil-btn">Editar</button>
		</form>
	</div>
</body>
</html>
{% endblock %}

Modelos/templates/verclientes.html
<!DOCTYPE html>
<html>
<head>
	<style>
		body {
			background-color: #f2f2f2;
			font-family: Arial, sans-serif;
			font-size: 16px;
		}

		.container {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 80vh;
		}

		.header {
			display: flex;
			justify-content: flex-end;
			padding: 10px;
			background-color: #f2f2f2;

		}

		.login-btn,
		.register-btn,
		.registrarclientes-btn,
		.salir-btn,
		.perfil-btn,
		.inicio-btn{
			background-color: #00008B;
			color: #ffffff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			font-size: 16px;
			cursor: pointer;
			margin-left: 10px;
		}

		.btn-borrar {
		    color: #fff;
		    background-color: #d9534f;
		    border-color: #d43f3a;
		}
		.btn-editar {
		    color: #fff;
		    background-color: #5cb85c;
		    border-color: #4cae4c;
		}
		.btn {
		    display: inline-block;
		    margin-bottom: 0;
		    font-weight: 400;
		    text-align: center;
		    white-space: nowrap;
		    vertical-align: middle;
		    -ms-touch-action: manipulation;
		    touch-action: manipulation;
		    cursor: pointer;
		    border: 1px solid transparent;
		    padding: 6px 12px;
		    font-size: 14px;
		    line-height: 1.42857143;
		    border-radius: 4px;
		}
		.login-btn:hover,
		.register-btn:hover,
		.registrarclientes-btn:hover,
		.salir-btn:hover,
		.perfil-btn:hover,
		.editar-btn:hover,
		.inicio-btn:hover{
			background-color: #0062cc;
		}

		h1 {
			color: #000000;
			margin-bottom: 40px;
		}

		h2 {
			color: #000000;
			margin-bottom: 40px;
		}
		h3 {
			color: #000000;
			margin-bottom: 30px;
		}
		h4 {
			color: #000000;
			margin-bottom: 30px;
		}


		form {
			background-color: #B0C4DE;
			border: 1px solid #dddddd;
			padding: 20px;
			border-radius: 10px;
			box-shadow: 0 0 10px rgba(0,0,0,0.1);
			width: 50%;
			text-align: center;
		}

		label {
			display: block;
			margin-bottom: 10px;
			color: #2F4F4F;
			text-align: left;
		}

		input[type="text"],
		input[type="email"] {
			padding: 10px;
			border: 1px solid #cccccc;
			border-radius: 5px;
			width: 100%;
			box-sizing: border-box;
			margin-bottom: 20px;
			font-size: 16px;
		}

		input[type="submit"] {
			background-color: #00008B;
			color: #ffffff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			font-size: 16px;
			cursor: pointer;
		}

		input[type="submit"]:hover {
			background-color: #0062cc;
		}
	</style>
	<title>Formulario de Clientes</title>
</head>
{% block contenido %}

<body>
	<div class="header">
		<div style="margin-right: auto; display: flex; justify-content: space-between;">
			<a class="inicio-btn" href="http://127.0.0.1:8000/">Inicio</a>
			<a class="inicio-btn" href="http://127.0.0.1:8000/registrodeclientes/">Registrar Cliente</a>
		</div>
		{% if request.user.is_authenticated %}
		<a class="perfil-btn" aria-current="page" href="http://127.0.0.1:8000/perfil/">{{user.username}}</a>
        <a class="salir-btn" aria-current="page" href="http://127.0.0.1:8000/logout/">Salir</a>
		{% endif %}
		{% if not request.user.is_authenticated %}
		<a class="login-btn" href="http://127.0.0.1:8000/login/">Login</a>
		<a class="register-btn" href="http://127.0.0.1:8000/registro/">Registro</a>
		{% endif %}
	</div>
	<div class="header"><a class="volver-btn" href="http://127.0.0.1:8000/registrodeclientes/">Volver</a></div>
	<div class="container">
		<form>
		<h1>CLIENTES REGISTRADOS</h1>
		{% for c in clientes %}
        <h3>{{c.nombre}} | {{c.apellido}} | {{c.mail}} | {{c.fecha_registro}}
		<a class="btn btn-editar" href="/editarcliente/{{c.id}}">Edit</a>
		<a class="btn btn-borrar" href="/borrarcliente/{{c.id}}">Borrar</a>
		</h3>
		{% endfor %}
		</form>
	</div>
</body>
</html>
{% endblock %}

RegistroDeClientes/templates/cambiarcontraseña.html
<!DOCTYPE html>
<html>
<head>
	<title>Formulario de Clientes</title>
	<style>
		body {
			background-color: #f2f2f2;
			font-family: Arial, sans-serif;
			font-size: 16px;
		}

		.container {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 90vh;
		}

		.header {
			display: flex;
			justify-content: flex-end;
			padding: 10px;
			background-color: #f2f2f2;

		}

		.login-btn,
		.register-btn,
		.salir-btn,
		.perfil-btn,
		.inicio-btn{
			background-color: #00008B;
			color: #ffffff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			font-size: 16px;
			cursor: pointer;
			margin-left: 10px;
		}

		.login-btn:hover,
		.register-btn:hover,
		.salir-btn:hover,
		.perfil-btn:hover,
		.inicio-btn:hover{
			background-color: #0062cc;
		}

		h2 {
			color: #000000;
			margin-bottom: 30px;
		}

		form {
			background-color: #B0C4DE;
			border: 1px solid #dddddd;
			padding: 20px;
			border-radius: 10px;
			box-shadow: 0 0 10px rgba(0,0,0,0.1);
			width: 400px;
			text-align: center;
		}

		label {
			display: block;
			margin-bottom: 10px;
			color: #2F4F4F;
			text-align: left;
		}

		input[type="text"],
		input[type="email"],
		input[type="date"],
		input[type="password"]{
			padding: 10px;
			border: 1px solid #cccccc;
			border-radius: 5px;
			width: 100%;
			box-sizing: border-box;
			margin-bottom: 20px;
			font-size: 16px;
		}

		input[type="submit"] {
			background-color: #00008B;
			color: #ffffff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			font-size: 16px;
			cursor: pointer;
		}

		input[type="submit"]:hover {
			background-color: #0062cc;
		}
	</style>
</head>
{% block contenido %}
<body>
	<div class="header">
		<div style="margin-right: auto; display: flex; justify-content: space-between;">
			<a class="inicio-btn" href="http://127.0.0.1:8000/">Inicio</a>
			<a class="inicio-btn" href="http://127.0.0.1:8000/registrodeclientes/">Registrar Cliente</a>
		</div>
		{% if request.user.is_authenticated %}
		<a class="perfil-btn" aria-current="page" href="http://127.0.0.1:8000/perfil/">{{user.username}}</a>
        <a class="salir-btn" aria-current="page" href="http://127.0.0.1:8000/logout/">Salir</a>
		{% endif %}
		{% if not request.user.is_authenticated %}
		<a class="login-btn" href="http://127.0.0.1:8000/login/">Login</a>
		<a class="register-btn" href="http://127.0.0.1:8000/registro/">Registro</a>
		{% endif %}
	</div>
	<div class="container">
		<form method = "POST" >
			{% csrf_token %}
			<table>
				<h1>CAMBIAR CONTRASEÑA</h1>
				<h1> {{ user.username }} </h1>
				<input type="password" name="old_password" placeholder="Contraseña anterior" required="" id="id_old_password">
				<input type="password" name="new_password1" placeholder="Contraseña nueva" required="" id="id_new_password1">
				<input type="password" name="new_password2" placeholder="Confirmar contraseña nueva" required="" id="id_new_password2">
			</table>
			<button type="submit" class="perfil-btn" >Cambiar contraseña</button>
		</form>
	</div>
</body>
</html>
{% endblock %}

RegistroDeClientes/templates/editarperfil.html
<!DOCTYPE html>
<html>
<head>
	<title>Formulario de Clientes</title>
	<style>
		body {
			background-color: #f2f2f2;
			font-family: Arial, sans-serif;
			font-size: 16px;
		}

		.container {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 90vh;
		}

		.header {
			display: flex;
			justify-content: flex-end;
			padding: 10px;
			background-color: #f2f2f2;

		}

		.login-btn,
		.register-btn,
		.salir-btn,
		.perfil-btn,
		.inicio-btn{
			background-color: #00008B;
			color: #ffffff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			font-size: 16px;
			cursor: pointer;
			margin-left: 10px;
		}

		.login-btn:hover,
		.register-btn:hover,
		.salir-btn:hover,
		.perfil-btn:hover,
		.inicio-btn:hover{
			background-color: #0062cc;
		}

		h2 {
			color: #000000;
			margin-bottom: 30px;
		}

		form {
			background-color: #B0C4DE;
			border: 1px solid #dddddd;
			padding: 20px;
			border-radius: 10px;
			box-shadow: 0 0 10px rgba(0,0,0,0.1);
			width: 400px;
			text-align: center;
		}

		label {
			display: block;
			margin-bottom: 10px;
			color: #2F4F4F;
			text-align: left;
		}

		input[type="text"],
		input[type="email"],
		input[type="date"]{
			padding: 10px;
			border: 1px solid #cccccc;
			border-radius: 5px;
			width: 100%;
			box-sizing: border-box;
			margin-bottom: 20px;
			font-size: 16px;
		}

		input[type="submit"] {
			background-color: #00008B;
			color: #ffffff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			font-size: 16px;
			cursor: pointer;
		}

		input[type="submit"]:hover {
			background-color: #0062cc;
		}
	</style>
</head>
{% block contenido %}
<body>
	<div class="header">
		<div style="margin-right: auto; display: flex; justify-content: space-between;">
			<a class="inicio-btn" href="http://127.0.0.1:8000/">Inicio</a>
			<a class="inicio-btn" href="http://127.0.0.1:8000/registrodeclientes/">Registrar Cliente</a>
		</div>
		{% if request.user.is_authenticated %}
		<a class="perfil-btn" aria-current="page" href="http://127.0.0.1:8000/perfil/">{{user.username}}</a>
        <a class="salir-btn" aria-current="page" href="http://127.0.0.1:8000/logout/">Salir</a>
		{% endif %}
		{% if not request.user.is_authenticated %}
		<a class="login-btn" href="http://127.0.0.1:8000/login/">Login</a>
		<a class="register-btn" href="http://127.0.0.1:8000/registro/">Registro</a>
		{% endif %}
	</div>
	<div class="container">
		<form method = "POST" >
			{% csrf_token %}
			<table>
				<h1>EDITAR PERFIL</h1>
				<h1> {{ user.username }} </h1>
				{{ form.as_table}}
			</table>
			<a class="perfil-btn" href="http://127.0.0.1:8000/cambiarcontraseña/"> Cambiar Contraseña <br></a><br>
			<button type="submit" class="perfil-btn" >Editar perfil</button>
		</form>
	</div>
</body>
</html>
{% endblock %}